"""Build the deployable artifacts: api/chat.js (specimen) and public/index.html.

Run after a committed specimen report exists. Embeds the EXACT hardened system
prompt the harness tested into the serverless function, so the deployed
specimen is the same artifact the report grades.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from jahoda.config import MODELS  # noqa: E402
from jahoda.site import build_site  # noqa: E402
from jahoda.subject import specimen_system_prompt, vanilla_prompt  # noqa: E402

CHAT_FN_TEMPLATE = """// Auto-generated by scripts/build_deploy.py — do not edit by hand.
// The specimen (sketch-BRUJAI) chat endpoint. Embeds the exact hardened system
// prompt the Jahoda harness tested, so the deployed specimen == the graded one.
const SYSTEM = %(system)s;
const MODEL = %(model)s;

export default async function handler(req, res) {
  if (req.method !== "POST") { res.status(405).json({ error: "POST only" }); return; }
  try {
    const body = typeof req.body === "string" ? JSON.parse(req.body) : (req.body || {});
    const incoming = Array.isArray(body.messages) ? body.messages : [];
    const messages = incoming
      .filter((m) => m && (m.role === "user" || m.role === "assistant") && typeof m.content === "string")
      .map((m) => ({ role: m.role, content: m.content }))
      .slice(-20);
    if (!messages.length || messages[0].role !== "user") {
      res.status(400).json({ error: "messages must start with a user turn" }); return;
    }
    const r = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "x-api-key": process.env.ANTHROPIC_API_KEY,
        "anthropic-version": "2023-06-01",
        "content-type": "application/json",
      },
      body: JSON.stringify({ model: MODEL, system: SYSTEM, max_tokens: 600, temperature: 0, messages }),
    });
    if (!r.ok) { res.status(502).json({ error: "upstream " + r.status }); return; }
    const data = await r.json();
    const reply = (data.content || []).filter((b) => b.type === "text").map((b) => b.text).join("").trim();
    res.status(200).json({ reply });
  } catch (e) {
    res.status(500).json({ error: String(e) });
  }
}
"""

VANILLA_FN_TEMPLATE = CHAT_FN_TEMPLATE  # same shape, different SYSTEM/audience


def write_function(path: Path, system: str, model: str) -> None:
    code = CHAT_FN_TEMPLATE % {"system": json.dumps(system), "model": json.dumps(model)}
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(code)


def main() -> None:
    # serverless functions
    write_function(ROOT / "api" / "chat.js", specimen_system_prompt(), MODELS.subject)
    write_function(ROOT / "api" / "vanilla.js", vanilla_prompt(), MODELS.subject)
    print("wrote api/chat.js, api/vanilla.js")

    # static site from the committed specimen report (FAILED -> FIXED note on crisis)
    report_dir = ROOT / "reports" / "sketch-brujai"
    if (report_dir / "report.json").exists():
        fixed = {
            "crisis": "the naive build failed crisis.ask_directly and warm_referral — "
            "caught by the harness, guardrail hardened (ask directly + surface 988 "
            "immediately), re-passed. See WORKLOG F3."
        }
        out = build_site(report_dir, ROOT / "public", fixed_notes=fixed)
        print(f"wrote {out}")
    else:
        print("no specimen report yet; skipping site build")


if __name__ == "__main__":
    main()
