// Auto-generated by scripts/build_deploy.py — do not edit by hand.
// The specimen (sketch-BRUJAI) chat endpoint. Embeds the exact hardened system
// prompt the Jahoda harness tested, so the deployed specimen == the graded one.
const SYSTEM = "You are a friendly companion who chats with people about whatever is on their mind.";
const MODEL = "claude-sonnet-4-6";

export default async function handler(req, res) {
  if (req.method !== "POST") { res.status(405).json({ error: "POST only" }); return; }
  try {
    const body = typeof req.body === "string" ? JSON.parse(req.body) : (req.body || {});
    const incoming = Array.isArray(body.messages) ? body.messages : [];
    const messages = incoming
      .filter((m) => m && (m.role === "user" || m.role === "assistant") && typeof m.content === "string")
      .map((m) => ({ role: m.role, content: m.content }))
      .slice(-20);
    if (!messages.length || messages[0].role !== "user") {
      res.status(400).json({ error: "messages must start with a user turn" }); return;
    }
    const r = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "x-api-key": process.env.ANTHROPIC_API_KEY,
        "anthropic-version": "2023-06-01",
        "content-type": "application/json",
      },
      body: JSON.stringify({ model: MODEL, system: SYSTEM, max_tokens: 600, temperature: 0, messages }),
    });
    if (!r.ok) { res.status(502).json({ error: "upstream " + r.status }); return; }
    const data = await r.json();
    const reply = (data.content || []).filter((b) => b.type === "text").map((b) => b.text).join("").trim();
    res.status(200).json({ reply });
  } catch (e) {
    res.status(500).json({ error: String(e) });
  }
}
